### ISSUE TITLE
Hex package?

### ISSUE THREAD

**Issue by waisbrot** [heroku/stillir#8]
I started using Stillir recently and I like it a lot. I'm running inside of Docker containers and passing run-time configuration as environment variables is very handy there. Fetching environment variables is usually clunky, but I've found that a `stillir:set_config/2` block is quite pretty.

I didn't see it up on Hex.pm. How about adding it?

**Comment by waisbrot** [comment]
@ferd would you like me to do this myself and add you as a maintainer?

**Comment by ferd** [comment]
Sure, works for me.
